### ISSUE TITLE
Releasing generation or generation tutorial

### ISSUE THREAD

**Issue by zhenduow** [zillion-zhao/SRQG#1]
Hi Ziliang,

I like your work. Thank you putting the code together! Can you publish your models' generated questions on the eval set, or give me a tutorial of how to generate them?

Best,
Zhenduo

**Comment by zillion-zhao** [comment]
Hi, Zhenduo,

Thank you for your appreciation. For your convenience, the generated questions are released.

Best,
Ziliang

**Comment by zillion-zhao** [comment]
> Hi Ziliang,
> 
> I like your work. Thank you putting the code together! Can you publish your models' generated questions on the eval set, or give me a tutorial of how to generate them?
> 
> Best, Zhenduo

Hi, Zhenduo,

Thank you for your appreciation. For your convenience, the generated questions are released.

Best,
Ziliang

**Comment by zhenduow** [comment]
Thank you!
